kumuluzee:
  name: bank-accounts
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BankDS
      connection-url: jdbc:postgresql://localhost:5432/bank
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
rest-properties:
  external-services:
    transaction-service:
      enabled: true