apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-accounts-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-accounts
    spec:
      containers:
        - image: postgres:9.6.3
          name: postgres-accounts
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGREs_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: accounts
          ports:
          - containerPort: 5432
            protocol: TCP