apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-accounts-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-accounts
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-accounts
          env:
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: accounts
          ports:
          - containerPort: 5432
            protocol: TCP